package com.hbm.saveddata.satellites.intel;

public enum IntelClassification {
	NATURAL,
	STRUCTURE,
	REINFORCED_STRUCTURE,
	MACHINERY,
	POWER,
	COMMUNICATIONS,
	LAUNCH_INFRASTRUCTURE,
	CAVITY,
	TUNNEL,
	BUNKER,
	POSSIBLE_SILO
}
